Build multi-platform docker images
Build images for both amd64 and arm64 to support Graviton EC2 instances.

Use docker save/load for intermediate artifacts. This has the added benefit
of tagging and pushing the same image that Trivy scanned, instead of
building a new image.

https://docs.docker.com/build/ci/github-actions/multi-platform/

diff --git a/.github/workflows/docker_build.yml b/.github/workflows/docker_build.yml
--- a/.github/workflows/docker_build.yml
+++ b/.github/workflows/docker_build.yml
@@ -20,34 +20,80 @@ on:
 
 env:
   TARFILE_NAME: image.tar
+  IMAGE_NAME: test-image
 
 jobs:
-  tests:
-    runs-on: ubuntu-latest
+  build:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - platform: amd64
+            runner: ubuntu-24.04
+          - platform: arm64
+            runner: ubuntu-24.04-arm
+
+    runs-on: ${{ matrix.runner }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
           ref: ${{ inputs.REF_TO_CHECKOUT }}
 
-      - name: Static Analysis
-        uses: pre-commit/action@v3.0.0
+      - name: Build platform-specific Docker image
+        run: |
+          docker build \
+            --platform linux/${{ matrix.platform }} \
+            -t ${{ env.IMAGE_NAME }}:${{ matrix.platform }} \
+            .
 
-      - name: Check that build works, save for scanning, but don't push yet
-        uses: docker/build-push-action@v6.4.0
+          docker save \
+            ${{ env.IMAGE_NAME }}:${{ matrix.platform }} \
+            -o ${{ env.IMAGE_NAME }}.${{ matrix.platform }}.tar
+
+      - name: Upload image output for this platform
+        uses: actions/upload-artifact@v4
         with:
-          context: .
-          push: false
-          outputs: type=tar,dest=${{ env.TARFILE_NAME }}
+          name: image-${{ matrix.platform }}
+          path: ${{ env.IMAGE_NAME }}.${{ matrix.platform }}.tar
+          retention-days: 1
+
+  multi-platform:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download images
+        uses: actions/download-artifact@v4
+        with:
+          merge-multiple: true
+          pattern: image-*
+
+      - name: Build multi-platform image
+        run: |
+          # Exit on error and echo commands
+          set -ex
+
+          # Import platform-specific images
+          docker load -i ${{ env.IMAGE_NAME }}.amd64.tar
+          docker load -i ${{ env.IMAGE_NAME }}.arm64.tar
+
+          # Save both images in a single tarball
+          docker save \
+            ${{ env.IMAGE_NAME }}:amd64 \
+            ${{ env.IMAGE_NAME }}:arm64 \
+            -o ${{ env.TARFILE_NAME }}
 
       - name: Upload tarball for use by Trivy job
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.TARFILE_NAME }}
           path: ${{ env.TARFILE_NAME }}
+          retention-days: 1
 
     outputs:
-      tarfile_artifact: ${{ env.TARFILE_NAME }}
+      image_name: ${{ env.IMAGE_NAME }}
+      tarfile_name: ${{ env.TARFILE_NAME }}
 
     permissions:
       contents: read
@@ -55,12 +101,12 @@ jobs:
       packages: write
 
   trivy-scan:
-    needs: tests
+    needs: multi-platform
     uses: "./.github/workflows/trivy.yml"
     with:
       SOURCE_TYPE: tar
-      IMAGE_NAME: image-name
-      TARFILE_NAME: ${{ needs.tests.outputs.tarfile_artifact }}
+      IMAGE_NAME: ${{ needs.multi-platform.outputs.image_name }}
+      TARFILE_NAME: ${{ needs.multi-platform.outputs.tarfile_name }}
       EXIT_CODE: 1
     permissions:
       contents: read
@@ -69,7 +115,7 @@ jobs:
 
   push-image:
     if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
-    needs: [tests, trivy-scan]
+    needs: [multi-platform, trivy-scan]
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -83,15 +129,25 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      - name: Download multi-platform image
+        uses: actions/download-artifact@v4
         with:
-          ref: ${{ inputs.REF_TO_CHECKOUT }}
+          name: ${{ env.TARFILE_NAME }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v6.4.0
-        with:
-          context: .
-          push: true
-          tags: ${{ inputs.IMAGE_REFERENCES }}
+      - name: Load, tag, and push multi-platform image
+        run: |
+          docker load -i ${{ env.TARFILE_NAME }}
+
+          for tag in ${{ inputs.IMAGE_REFERENCES }}
+          do
+            # Tag and push platform-specific images
+            docker tag ${{ env.IMAGE_NAME }}:amd64 "${tag}-amd64"
+            docker tag ${{ env.IMAGE_NAME }}:arm64 "${tag}-arm64"
+            docker push "${tag}-amd64"
+            docker push "${tag}-arm64"
+
+            # Create and push multi-platform manifest
+            docker manifest create "${tag}" "${tag}-amd64" "${tag}-arm64"
+            docker manifest push "${tag}"
+          done
 ...
